tenant: public
namespace: default
name: directory-source

className: com.rahullokurte.pulsario.source.DirectorySource
topicName: "persistent://public/default/directory-scan"
parallelism: 1
processingGuarantees: ATLEAST_ONCE

configs:
  inputDir: "/tmp/input"
  processedDir: "/tmp/processed"
  frequency: "2"